---
- name: Install Minikube
  shell: |
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    install minikube-linux-amd64 /usr/local/bin/minikube
  args:
    creates: /usr/local/bin/minikube

- name: Delete existing Minikube cluster (if any)
  command: minikube delete --all
  ignore_errors: true  # Ignore errors in case Minikube is not initialized yet

- name: Start Minikube with Docker driver
  command: minikube start --driver=docker
  environment:
    MINIKUBE_IN_STYLE: "false"  # Optional: disables colored output for cleaner logs

