---
- name: Install Minikube (as root)
  become: true
  shell: |
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    install minikube-linux-amd64 /usr/local/bin/minikube
  args:
    creates: /usr/local/bin/minikube

- name: Delete existing Minikube cluster (if any)
  become: true
  command: minikube delete --all
  ignore_errors: true

- name: Start Minikube with Docker driver (as non-root user)
  become: false
  command: minikube start --driver=docker
  environment:
    MINIKUBE_IN_STYLE: "false"
