---
- name: Install Docker
  shell: |
    curl -fsSL https://get.docker.com | sh
    usermod -aG docker $USER
  args:
    creates: /usr/bin/docker

- name: Install kubectl
  shell: |
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/kubectl
