- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Install essential packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - curl
    - wget
    - git
    - unzip
    - python3-pip
  become: true
