apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: divypagariya/ml-backend:latest  # Your backend Docker image
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: dockerhub-secret  # This tells Kubernetes to use the secret to pull the image

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort
