- name: Install Minikube dependencies (kubectl)
  apt:
    name: apt-transport-https
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Kubernetes APT repository for kubectl
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  when: ansible_os_family == 'Debian'

- name: Add Kubernetes APT repository to APT sources
  apt_repository:
    repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
    state: present
  when: ansible_os_family == 'Debian'

- name: Install kubectl from Kubernetes repository
  apt:
    name: kubectl
    state: present
  when: ansible_os_family == 'Debian'

- name: Download and install Minikube
  get_url:
    url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    dest: /usr/local/bin/minikube
    mode: '0755'
  when: ansible_os_family == 'Debian'

- name: Start Minikube cluster using Docker driver
  command: minikube start --driver=docker
  become: true
  become_user: "{{ ansible_user }}"
  environment:
    CHANGE_MINIKUBE_NONE_USER: true
  when: ansible_os_family == 'Debian'

- name: Verify Minikube status
  command: minikube status
  register: minikube_status
  changed_when: false
  failed_when: "'Running' not in minikube_status.stdout"

- name: Get Minikube IP
  command: minikube ip
  register: minikube_ip
  changed_when: false

- name: Display Minikube IP
  debug:
    msg: "Minikube is running at {{ minikube_ip.stdout }}"
