---
- name: Install common dependencies (Docker, Python, Git)
  hosts: all_servers
  become: true
  roles:
    - common

- name: Set up Kubernetes (Minikube)
  hosts: localhost
  become: true
  roles:
    - kubernetes

- name: Deploy ELK Stack
  hosts: localhost
  become: true
  roles:
    - elk