- name: Install Minikube and kubectl
  shell: |
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    install minikube-linux-amd64 /usr/local/bin/minikube
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/minikube
    
- name: Ensure Minikube is not running from previous failed start
  shell: minikube delete || true
  ignore_errors: true

- name: Start Minikube
  shell: minikube start --driver=docker --ports=30080:30080,30000:30000
  become: false
  environment:
    PATH: "{{ ansible_env.PATH }}"

