- name: Install Minikube and kubectl
  shell: |
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    install minikube-linux-amd64 /usr/local/bin/minikube
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/minikube

- name: Remove any stale mlops.local entries BEFORE starting Minikube
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: '.*mlops\.local'
    state: absent
    
- name: Clean up old Minikube and Kubernetes configs
  shell: |
    minikube delete --all --purge
    rm -rf ~/.minikube ~/.kube
  ignore_errors: true



- name: Start Minikube
  shell: minikube start --driver=docker 
  become: false
  environment:
    PATH: "{{ ansible_env.PATH }}"

- name: Enable Ingress controller in Minikube
  shell: minikube addons enable ingress
  become: false
  environment:
    PATH: "{{ ansible_env.PATH }}"

- name: Add mlops.local to /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ lookup('pipe', 'minikube ip') }} mlops.local"
    state: present
