- name: Install Minikube and kubectl
  shell: |
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    install minikube-linux-amd64 /usr/local/bin/minikube
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/minikube

- name: Remove any stale mlops.local entries from /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: '.*mlops\.local'
    state: absent

- name: Thorough Minikube and Docker cleanup
  shell: |
    minikube stop || true
    minikube delete --all --purge || true
    docker container rm -f $(docker ps -aq) || true   
    docker volume prune -f || true                    
    docker network prune -f || true
    rm -rf ~/.minikube ~/.kube ~/.config/minikube
    docker system prune -a -f || true
  ignore_errors: true


- name: Sleep for a moment to ensure cleanup is complete
  pause:
    seconds: 10

- name: Start Minikube
  shell: minikube start --driver=docker 
  become: false
  environment:
    PATH: "{{ ansible_env.PATH }}"

- name: Enable Ingress controller in Minikube
  shell: minikube addons enable ingress
  become: false
  environment:
    PATH: "{{ ansible_env.PATH }}"

- name: Add mlops.local to /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ lookup('pipe', 'minikube ip') }} mlops.local"
    state: present