- name: Install Minikube and kubectl
  shell: |
    curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    install minikube-linux-amd64 /usr/local/bin/minikube
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/minikube

- name: Remove any stale mlops.local entries from /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    regexp: '.*mlops\.local'
    state: absent
    
- name: Thorough Minikube cleanup
  shell: |
    minikube stop || true
    minikube delete --all --purge || true
    docker container rm -f $(docker ps -a -q --filter "name=minikube") || true
    docker container rm -f $(docker ps -a -q --filter "name=k8s_") || true
    docker network prune -f || true
    rm -rf ~/.minikube ~/.kube
    docker system prune -f || true
  ignore_errors: true

- name: Sleep for a moment to ensure cleanup is complete
  pause:
    seconds: 15

- name: Check Docker service status
  service:
    name: docker
    state: started
  become: true

- name: Create minikube config directory
  file:
    path: ~/.minikube
    state: directory
    mode: '0755'

- name: Start Minikube
  shell: minikube start --driver=docker 
  become: false
  environment:
    PATH: "{{ ansible_env.PATH }}"
    DOCKER_HOST: "unix:///var/run/docker.sock"
    NO_PROXY: "localhost,127.0.0.1,192.168.49.0/24,192.168.58.0/24,10.96.0.0/12"


- name: Enable Ingress controller in Minikube
  shell: minikube addons enable ingress
  become: false
  environment:
    PATH: "{{ ansible_env.PATH }}"
  register: enable_ingress
  retries: 3
  delay: 10
  until: enable_ingress.rc == 0

- name: Get minikube IP
  shell: minikube ip
  become: false
  register: minikube_ip
  environment:
    PATH: "{{ ansible_env.PATH }}"

- name: Add mlops.local to /etc/hosts
  become: true
  lineinfile:
    path: /etc/hosts
    line: "{{ minikube_ip.stdout }} mlops.local"
    state: present