version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    container_name: movie-backend

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    container_name: movie-frontend
    depends_on:
      - backend
